name: Bundle & Package

on:
  push:
    branches: [ "master" ]
    
  pull_request:
    branches: [ "master" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3.3.0

      - name: Package
        uses: BigWigsMods/packager@v2.0.3
        with:
           args: -d false 

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Addon
          path: /home/runner/work/BapesAutoMerge/BapesAutoMerge/.release/*.zip
