name: Bundle & Package

on:
  push:
    branches: [ "master" ]
    
  pull_request:
    branches: [ "master" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3.3.0
        
#       - name: Set Working Directory
#         run: |
#           cd ./src
#           ls

      - name: Package
        uses: BigWigsMods/packager@v2.0.3
