name: Publish

on:
  push:
    branches: [ "master" ]
    
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Clone
        uses: actions/checkout@v3.5.3

      - name: Package
        uses: BigWigsMods/packager@v2.1.0

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Addon
          path: /home/runner/work/BapesAutoMerge/BapesAutoMerge/.release/*.zip
